### ISSUE TITLE
config file name can be supplied to get_version() but not to command-line program

### ISSUE THREAD

**Issue by metaperl** [jwodder/versioningit#22]
Because we use setup.py I renamed `pyproject.toml` to `versioningit.toml` to avoid any possibility of the CICD server using the toml file to build the project.

Even though I am experiencing an import error in setup.py for the line `from versioningit import get_version`, I feel better about debugging it because I have the file renamed.

But there is no way to test the new file via the command-line program because it lacks an option to specify the config file (unlike `get_version()` which does.

**Comment by jwodder** [comment]
> Because we use setup.py I renamed `pyproject.toml` to `versioningit.toml` to avoid any possibility of the CICD server using the toml file to build the project.

That doesn't follow.  You can still build `setup.py`-based projects using `pyproject.toml`; you just need to include in your `pyproject.toml`:

```toml
[build-system]
requires = ["setuptools", "wheel"]  # "versioningit" also goes here if you're using it
build-backend = "setuptools.build_meta"
```

(See also this article: [Why you shouldn't invoke setup.py directly](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html))

In fact, you *need* to use a `pyproject.toml` if you want to build your project with `versioningit`, as otherwise `versioningit` won't be present in the build environment (hence the import errors you're experiencing).

Hence, if one is using versioningit, then 99.9999% of the time, there's going to be a `pyproject.toml`.  As a result, I see no reason to support alternative config file names.  Note also that `get_version()` does not support specifying the config file; it lets you support the project directory (which is expected to contain a `pyproject.toml`) and the configuration as a native Python structure, but not the config file.
