### ISSUE TITLE
Feature request: Write version as tuple to `tool.versioningit.write` -> `file`

### ISSUE THREAD

**Issue by posita** [jwodder/versioningit#32]
`setuptools_scm` writes the version both as a `str` and as a `tuple` (called `_version_as_tuple` of type `tuple[int | str, ...]`) similar to [`sys.version_info`](https://docs.python.org/3/library/sys.html#sys.version_info). This is especially useful when doing programmatic comparisons such as:

``` python
if sys.version_info >= (3, 8):
  …
```

Please consider offering a similar format when writing to `tool.versioningit.write` -> `file`. I realize `versioningit`'s flexibility on formats might frustrate this, but one could do something like the following and probably satisfy most use cases:

``` python
import re
from typing import Iterator

# split_on allows for possible end-user configuration, if desirable
def version_as_tuple(version: str, split_on = r"\.|\+") -> tuple[int | str, ...]:
  def _parts_as_int_or_str() -> Iterator[int | str]:
    for part in re.split(split_on, version):
      try:
        yield int(part)
      except ValueError:
        yield part
  return tuple(_parts_as_int_or_str())
```

**Comment by jwodder** [comment]
I like this idea, but I'm worried about users trying to order-compare these tuples in their entirety when epochs, pre-/post-/dev-releases, and/or local segments are involved.  Unfortunately, producing tuples that preserve PEP 440 version ordering for these features doesn't seem really practical or feasible in a non-ugly way, so (unless you or someone else has a better idea) I'll just implement a couple simple version-to-tuple routines and add a warning to the documentation about comparison.

Here's the plan I have for implementing this:

- Instead of receiving just a version, the "write" and "onbuild" steps will now receive a dict of fields to use in filling out their templates.
    - This will involve changing the signatures of various functions & methods in the public API, necessitating bumping `versioningit`'s version to 2.0.

- Add a `[tool.versioningit.template-fields]` subtable to the config for instructing `versioningit` how to derive the fields to pass to "write" and "onbuild".  This will come with a builtin "basic" method (the default) which produces the following set of fields:
    - `{version}` — same as before
    - the same fields as available to the `format` step, but with `{version}` renamed to `{base_version}` and `{branch}` not sanitized
    - `{version_tuple}` — a `repr()` of a tuple of version components; this is configured by the following options in a `[tool.versioningit.template-fields.version-tuple]` subtable:
        - `split-on` (regex, defaults to `[-_.+!]`) — The version is split apart on all matches of this regex
            - Capturing groups in the regex are ignored
            - This option is ignored when `pep440` is true
        - `double-quote` (bool, default True) — whether to use double-quotes around strings in the tuple (false for single-quotes)
        - `pep440` (bool, default False) — If true, instead of splitting on a regex, the version is parsed as a PEP 440 version with `packaging.version.Version`, and the normalized non-empty components are combined into a tuple
            - Examples:
                - "1.2.3a0" → (1, 2, 3, "a0")
                - "1.2.3.post1" → (1, 2, 3, "post1")
                - "1.2.3-1" → (1, 2, 3, "post1")
                - "1!2.3.4" → (1, 2, 3, 4) (but see the `epoch` option below)
                - "1.0.0.0" → (1, 0, 0, 0)
                - "1.2.3b1.post2.dev3+local.2022" → (1, 2, 3, "b1", "post2", "dev3", "+local.2022")
        - `epoch` (bool) — whether to include the epoch when parsing as a PEP 440 version; if omitted, the epoch is included iff it is nonzero
            - This option is ignored when `pep440` is false

Admittedly, I'm not entirely thrilled with this "`version-tuple` table inside `template-fields` table" setup, but it seems to be the simplest way to (a) provide a `{version_tuple}` placeholder and other placeholders (`{author_date}` etc.) to write & onbuild while (b) allowing users to override (via custom methods) the set of write+onbuild placeholders.

Thoughts?

**Comment by jwodder** [comment]
@posita

> Just to be clear, where pep440 is False, will the type of version-tuple be limited to tuple[str, ...]?

When `pep440` is false, integer components of the version will still be cast to `int`s, and then the whole tuple is `repr()`'d.  (E.g., if `{version}` is `1.2.3+local.2022`, then, using the default `split-on`, `{version_tuple}` will be `(1, 2, 3, "local", 2022)`.)  The only difference `pep440` makes is *how* the version gets split up, not what happens to it after it gets split up.

**Comment by jwodder** [comment]
`versioningit` v2.0 is out now, with support for `{version_tuple}` in write & onbuild templates.

**Comment by posita** [comment]
Woohoo! Thanks, @jwodder!
