### ISSUE TITLE
why default is not a semver?

### ISSUE THREAD

**Issue by yarikoptic** [jwodder/versioningit#4]
AFAIK
```
distance = "{version}.post{distance}+{vcs}{rev}"
```
is not a [semver](https://semver.org/).

**Comment by jwodder** [comment]
The default version formats are meant to produce [PEP 440](https://www.python.org/dev/peps/pep-0440/)-compliant versions, not semver versions.  While the two have some overlap, they are not the same, and it appears that the only form for a non-final release that is compatible with both forms is "`<version>+<build>`".  I see no advantage to strictly sticking to semver in the Python world, but I do see an advantage to incorporating the tag distance into a ".post" or ".dev" component instead of a local component.
