### ISSUE TITLE
Integrate with GitHub Actions

### ISSUE THREAD

**Issue by aghand0ur** [jwodder/versioningit#83]
Hi,

I am trying to use `versioningit` to bump my pkg version while deploying with GitHub Actions.
The first push successfully created version 0.0.0 at PyPI: https://test.pypi.org/project/geotils/0.0.0/

However, version is not being incremented in subsequent pushes. What did I miss in the following configuration?

pyproject.toml:
```
[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "geotils"
dynamic = ["version"]
dependencies = [
                ...,
		'versioningit',
]
requires-python = ">=3.10"
description = "geotils by GEOAI group"
readme = "README.md"
license = {text = "MIT License"}
keywords = ["geotils", "geospatial", "earth observation"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
]

[tool.versioningit.format]
distance = "{base_version}.post{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{base_version}.post{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[project.urls]
Homepage = "https://geogroup.ai/"
Documentation = "https://readthedocs.org/geotils"
Repository = "https://github.com/geoaigroup/geotils"
"Bug Tracker" = "https://github.com/geoaigroup/geotils/issues"
Changelog = "https://github.com/geoaigroup/geotils/blob/master/CHANGELOG.md"
[project.scripts]
geotils = "geotils.module:function"
```

GitHub CI/CD workflow code: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#the-whole-ci-cd-workflow

**Comment by jwodder** [comment]
`versioningit` needs to be listed in `requires` under `[build-system]` in order for it to be present & active when the package version is calculated.  Putting it in `[project]dependencies` as you've done is only correct if your package is a plugin for `versioningit`.

Also, I only skimmed the linked workflow, but I don't see where you're creating a new Git tag for each release; creating a tag is necessary in order to bump the version for a `versioningit`-using package.

**Comment by aghand0ur** [comment]
Thanks @jwodder for the quick feedback.

- I added `versioningit`  to the `requires` list
- got the following build error `versioningit could not find a version for the project in /home/runner/work/geotils/geotils!`
- Finally, the workflow is not creating a tag for each release on purpose. For releases to be pushed to test-pypi, there should be no attached tag while for releases to be pushed to main PyPi, a tag should be attached. This is the logic used by the workflow to decided where to publish (either test-pypi or regular pypi).
- given the workflow logic, any luck to use `versioningit`  without a tag?

**Comment by aghand0ur** [comment]
> What exactly are you expecting or wanting to happen in the absence of tags?
In the absence of a tag, it would be more than enough to increment the patch release version to be able to push changes to TestPyPI.

Would this be feasible with `versioningit` or do you recommend other version-bumping tools?

**Comment by jwodder** [comment]
@aghand0ur `versioningit` has no knowledge of any version information if there are no tags available, so it wouldn't have anything to increment if there are no tags.

The following may work for you instead:

- Change the `uses: actions/checkout@v4` step at the start of the `build` job to:

    ```yaml
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    ```

   This will cause the `checkout` action to perform a full checkout of all of your repository's history, including tags.  Without the `with: {fetch-depth: 0}`, it would just check out the commit that triggered the workflow, and there would be no tags available for `versioningit` to query.

   With this change, when you build the package, `versioningit` will take the latest tag (as identified by `git describe`); if there have been any commits since that tag, you'll get a version formatted as described in your `tool.versioningit.format.distance` config option.

- It is my understanding that both PyPI and Test PyPI reject uploads of packages whose versions end with `+stuff`.  Thus, you'll need to change your "distance" format to not contain a plus sign.

**Comment by aghand0ur** [comment]
A straightforward and uncomplicated solution...
I'm at a loss for words to express my gratitude, @jwodder.
